#!/bin/sh

if [ -f /etc/issue ] ; then
	if grep -qs 'openpli' cat /etc/issue; then
		echo "*********************************"
		echo "Found supported image!           "
		echo "                                 "

	elif grep -qs 'corvoboys' cat /etc/issue; then
		echo "*********************************"
		echo "Found supported image!           "
		echo "                                 "
	else
		echo "*********************************"
		echo "Not supported image! Aborted!    "
		echo "                                 "
		exit 1
	fi
else
	echo "*********************************"
	echo "Not supported image! Aborted!    "
	echo "                                 "
	exit 1
fi


exit 0

